### ISSUE TITLE
This package is registered twice in PyPi

### ISSUE THREAD

**Issue by ayalash** [getslash/mailboxer-python#9]
The registered names:
* mailboxer-python - with all released versions
* maiboxer - with only 1.0.0 from 21014

**Comment by ayalash** [comment]
@vmalloc Do we want to delete mailboxer (without '-python') from PyPi or update it to be alias to mailboxer-python?

**Comment by vmalloc** [comment]
IIRC we registered it as a placeholder so that mailboxer won't be snatched and made into something else, and then the confusion of names will cause issues...
